/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_example_stef_ndksample_MainActivity.h"
/* Header for class com_example_stef_ndksample_MainActivity */

/*
 * Class:     com_example_stef_ndksample_MainActivity
 * Method:    callNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_stef_ndksample_MainActivity_callNative
  (JNIEnv *env, jobject obj){
    return (*env) -> NewStringUTF(env, "NDK Sample Test!");
  }

